export enum BonusTypeEnum {
  LEVEL_UP = 'LEVEL_UP',
  RANK_UP = 'RANK_UP',
  RAKEBACK = 'RAKEBACK',
  WEEKLY_AWARD = 'WEEKLY_AWARD',
  MONTHLY_AWARD = 'MONTHLY_AWARD',
  WEEKLY_RACE_PRIZE = 'WEEKLY_RACE_PRIZE',
  WEEKLY_RELOAD = 'WEEKLY_RELOAD',
  PROMOCODE = 'PROMOCODE',
}
