export enum CurrencyEnum {
  USD = 'USD',
  EUR = 'EUR',
  MXN = 'MXN',
  BRL = 'BRL',
  JPY = 'JPY',
  IDR = 'IDR',
  CAD = 'CAD',
  CNY = 'CNY',
  DKK = 'DKK',
  KRW = 'KRW',
  INR = 'INR',
  PHP = 'PHP',
  TRY = 'TRY',
  NZD = 'NZD',
  ARS = 'ARS',
  RUB = 'RUB',
  VND = 'VND',
}
