import {
  AdminEntity,
  AffiliateCampaignEntity,
  AffiliateCommissionEntity,
  AffiliateCommissionHistoryEntity,
  AffiliateEarningsEntity,
  AffiliateWalletEntity,
  AssetEntity,
  BalanceHistoryEntity,
  BalanceStatisticEntity,
  BalanceVaultEntity,
  BalanceVaultHistoryEntity,
  BalanceWalletEntity,
  BlackjackGameEntity,
  BlogArticleEntity,
  BonusCalculationLogEntity,
  BonusNotificationEntity,
  BonusTransactionEntity,
  BonusVipTierEntity,
  ChatEntity,
  ChatMessageEntity,
  CrashBetEntity,
  CrashGameEntity,
  CrashGameStateEntity,
  CrashSeedEntity,
  CurrencyRateHistoryEntity,
  DailyGamblingStatsEntity,
  DefaultAvatarEntity,
  DiceBetEntity,
  FiatRateHistoryEntity,
  GameBetLimitsEntity,
  GameBetTypeLimitsEntity,
  GameConfigEntity,
  GameResultEntity,
  GameSessionEntity,
  HouseEdgeEntity,
  KenoGameEntity,
  LimboGameEntity,
  MailTokenEntity,
  MinesGameEntity,
  MonthlyRacePrizeEntity,
  NotificationEntity,
  PhoneVerificationEntity,
  PlinkoGameEntity,
  PromocodeAuditEntity,
  PromocodeClaimEntity,
  PromocodeEntity,
  ProviderCategoryEntity,
  ProviderDeveloperEntity,
  ProviderGameEntity,
  ProviderGameSessionEntity,
  RaceEntity,
  RaceParticipantEntity,
  RakebackEntity,
  RefreshTokenEntity,
  RouletteGame,
  SeedPairEntity,
  SelfExclusionEntity,
  SessionTrackingEntity,
  SlotImageEntity,
  SportsbookBetEntity,
  St8BonusEntity,
  SystemSettingEntity,
  TransactionEntity,
  UserAvatarEntity,
  UserBetEntity,
  UserEntity,
  UserGameFavoritesEntity,
  UserIgnoredUserEntity,
  UserModerationHistoryEntity,
  UserProviderGameFavoritesEntity,
  UserRecentGamesEntity,
  UserVerificationEntity,
  UserVipStatusEntity,
  VerificationBasicInfoEntity,
  VerificationDocumentEntity,
  VipTransferSubmissionEntity,
  WalletEntity,
  WeeklyRacePrizeEntity,
  WithdrawRequestEntity,
} from '@zetik/shared-entities';
import { DataSource } from 'typeorm';
import { PostgresConnectionOptions } from 'typeorm/driver/postgres/PostgresConnectionOptions';
import { databaseConfig } from './config/database.config';

export function getDataSourceConfig() {
  return {
    type: 'postgres',
    host: databaseConfig().host,
    port: databaseConfig().port,
    username: databaseConfig().username,
    password: databaseConfig().password,
    database: databaseConfig().database,
    extra: {
      searchPath: 'admin,affiliate,users,payments,balance,bonus,blog,games,chat,promocodes',
    },
    entities: [
      AdminEntity,
      UserEntity,
      UserAvatarEntity,
      DefaultAvatarEntity,
      UserIgnoredUserEntity,
      UserModerationHistoryEntity,
      UserVerificationEntity,
      VerificationBasicInfoEntity,
      VerificationDocumentEntity,
      SelfExclusionEntity,
      DailyGamblingStatsEntity,
      RefreshTokenEntity,
      SessionTrackingEntity,
      MailTokenEntity,
      PhoneVerificationEntity,
      NotificationEntity,
      TransactionEntity,
      WalletEntity,
      WithdrawRequestEntity,
      BalanceHistoryEntity,
      BalanceStatisticEntity,
      CurrencyRateHistoryEntity,
      FiatRateHistoryEntity,
      BalanceWalletEntity,
      BalanceVaultEntity,
      BalanceVaultHistoryEntity,
      GameSessionEntity,
      GameResultEntity,
      SeedPairEntity,
      SlotImageEntity,
      UserBetEntity,
      UserRecentGamesEntity,
      UserGameFavoritesEntity,
      UserProviderGameFavoritesEntity,
      BlackjackGameEntity,
      CrashBetEntity,
      CrashGameEntity,
      CrashSeedEntity,
      CrashGameStateEntity,
      DiceBetEntity,
      KenoGameEntity,
      LimboGameEntity,
      MinesGameEntity,
      PlinkoGameEntity,
      RouletteGame,
      HouseEdgeEntity,
      SportsbookBetEntity,
      GameConfigEntity,
      GameBetLimitsEntity,
      GameBetTypeLimitsEntity,
      BonusVipTierEntity,
      UserVipStatusEntity,
      BonusCalculationLogEntity,
      BonusTransactionEntity,
      BonusNotificationEntity,
      RakebackEntity,
      VipTransferSubmissionEntity,
      ProviderDeveloperEntity,
      ProviderGameEntity,
      ProviderCategoryEntity,
      ProviderGameSessionEntity,
      UserProviderGameFavoritesEntity,
      AssetEntity,
      ChatEntity,
      ChatMessageEntity,
      AffiliateCampaignEntity,
      AffiliateCommissionEntity,
      AffiliateCommissionHistoryEntity,
      AffiliateEarningsEntity,
      AffiliateWalletEntity,
      RaceEntity,
      RaceParticipantEntity,
      WeeklyRacePrizeEntity,
      MonthlyRacePrizeEntity,
      BlogArticleEntity,
      SystemSettingEntity,
      PromocodeEntity,
      PromocodeClaimEntity,
      PromocodeAuditEntity,
      St8BonusEntity,
    ],
    connectTimeoutMS: 3000,
    poolSize: 200,
    migrations: [__dirname + '/migrations/*{.ts,.js}'],
    synchronize: false, // Using migrations instead of sync
    logging: ['migration', 'schema', 'error', 'warn'],
  } as PostgresConnectionOptions;
}

export const AppDataSource = new DataSource(getDataSourceConfig());
