import { config } from 'dotenv';
import { join } from 'path';
config({
  quiet: true,
  path: [join(process.cwd(), 'apps/admin-panel/.env'), join(process.cwd(), '.env')],
});

import {
  AdminAuditLogEntity,
  AdminEntity,
  AffiliateCampaignEntity,
  AffiliateCommissionEntity,
  ApiKeyEntity,
  AssetEntity,
  BalanceWalletEntity,
  BlogArticleEntity,
  BonusTransactionEntity,
  BonusVipTierEntity,
  CurrencyRateHistoryEntity,
  DefaultAvatarEntity,
  GameBetLimitsEntity,
  GameBetTypeLimitsEntity,
  GameConfigEntity,
  HouseEdgeEntity,
  PromocodeAuditEntity,
  PromocodeClaimEntity,
  PromocodeEntity,
  ProviderCategoryEntity,
  ProviderDeveloperEntity,
  ProviderGameEntity,
  SeedPairEntity,
  SelfExclusionEntity,
  SlotImageEntity,
  St8BonusEntity,
  SystemSettingEntity,
  TransactionEntity,
  UserAvatarEntity,
  UserEntity,
  UserVipStatusEntity,
  VipTransferSubmissionEntity,
  WeeklyRacePrizeEntity,
  WithdrawRequestEntity,
} from '@zetik/shared-entities';
import { DataSource } from 'typeorm';

export const AppDataSource = new DataSource({
  type: 'postgres',
  host: process.env.DB_HOST || 'localhost',
  port: parseInt(process.env.DB_PORT || '5432'),
  username: process.env.DB_USERNAME || 'postgres',
  password: process.env.DB_PASSWORD || '',
  database: process.env.DB_DATABASE || 'zetik',
  extra: {
    searchPath: 'admin,affiliate,users,payments,balance,bonus,blog,games,chat,promocodes',
  },
  entities: [
    AdminEntity,
    AdminAuditLogEntity,
    ApiKeyEntity,
    SystemSettingEntity,
    BalanceWalletEntity,
    BlogArticleEntity,
    BonusTransactionEntity,
    BonusVipTierEntity,
    WeeklyRacePrizeEntity,
    UserVipStatusEntity,
    VipTransferSubmissionEntity,
    UserEntity,
    UserAvatarEntity,
    DefaultAvatarEntity,
    TransactionEntity,
    WithdrawRequestEntity,
    CurrencyRateHistoryEntity,
    AssetEntity,
    AffiliateCampaignEntity,
    AffiliateCommissionEntity,
    GameConfigEntity,
    GameBetLimitsEntity,
    GameBetTypeLimitsEntity,
    HouseEdgeEntity,
    ProviderDeveloperEntity,
    ProviderCategoryEntity,
    ProviderGameEntity,
    PromocodeEntity,
    PromocodeClaimEntity,
    PromocodeAuditEntity,
    ProviderCategoryEntity,
    ProviderDeveloperEntity,
    ProviderGameEntity,
    St8BonusEntity,
    SeedPairEntity,
    SelfExclusionEntity,
    SlotImageEntity,
  ],
  connectTimeoutMS: 3000,
  poolSize: 100,
  migrations: [],
  synchronize: false,
  logging: ['schema', 'error', 'warn'],
});
